"""Tests for scripts/llm_driver.py (Phase 5)."""
from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path
from unittest.mock import MagicMock, patch

from scripts.llm_driver import _check_model_available, call_ollama, run


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _make_stream_response(tokens: list[str]) -> MagicMock:
    """Build a mock HTTP response that yields streamed Ollama JSON lines."""
    lines = [
        json.dumps({"response": t, "done": False}).encode() for t in tokens
    ]
    lines.append(json.dumps({"response": "", "done": True}).encode())

    mock_resp = MagicMock()
    mock_resp.__iter__ = MagicMock(return_value=iter(lines))
    mock_resp.__enter__ = MagicMock(return_value=mock_resp)
    mock_resp.__exit__ = MagicMock(return_value=False)
    return mock_resp


def _make_tags_response(models: list[str]) -> MagicMock:
    """Build a mock HTTP response for /api/tags."""
    body = json.dumps({"models": [{"name": m} for m in models]}).encode()
    mock_resp = MagicMock()
    mock_resp.read = MagicMock(return_value=body)
    mock_resp.__enter__ = MagicMock(return_value=mock_resp)
    mock_resp.__exit__ = MagicMock(return_value=False)
    return mock_resp


# ---------------------------------------------------------------------------
# _check_model_available
# ---------------------------------------------------------------------------

class CheckModelAvailableTests(unittest.TestCase):
    def test_passes_when_model_listed(self) -> None:
        with patch("urllib.request.urlopen", return_value=_make_tags_response(["qwen2.5:14b"])):
            _check_model_available("qwen2.5:14b")  # should not raise

    def test_raises_when_model_missing(self) -> None:
        with patch("urllib.request.urlopen", return_value=_make_tags_response(["llama3.1:8b"])):
            with self.assertRaises(ValueError) as ctx:
                _check_model_available("qwen2.5:14b")
        self.assertIn("qwen2.5:14b", str(ctx.exception))
        self.assertIn("llama3.1:8b", str(ctx.exception))

    def test_raises_connection_error_when_ollama_unreachable(self) -> None:
        from urllib.error import URLError
        with patch("urllib.request.urlopen", side_effect=URLError("refused")):
            with self.assertRaises(ConnectionError):
                _check_model_available("qwen2.5:14b")


# ---------------------------------------------------------------------------
# call_ollama
# ---------------------------------------------------------------------------

class CallOllamaTests(unittest.TestCase):
    def test_assembles_streamed_tokens(self) -> None:
        tokens = ["Hello", " world", "!"]
        with patch("urllib.request.urlopen", return_value=_make_stream_response(tokens)):
            result = call_ollama("test prompt", "qwen2.5:14b")
        self.assertEqual(result, "Hello world!")

    def test_empty_response(self) -> None:
        with patch("urllib.request.urlopen", return_value=_make_stream_response([])):
            result = call_ollama("test prompt", "qwen2.5:14b")
        self.assertEqual(result, "")


# ---------------------------------------------------------------------------
# run() integration
# ---------------------------------------------------------------------------

MINIMAL_PROMPT_PACK = """\
# Compilation Request

- Requested title: Test Topic
- Canonical title: Test Topic
- Canonical slug: test-topic
- Note category: topic
- Repository phase: Phase 3 compilation workflow
- Required generation method value: prompt_pack

# Instructions

Synthesize a compiled note.

# Desired Output Template

```markdown
---
title: "Test Topic"
note_type: "topic"
compiled_from: []
date_compiled: "YYYY-MM-DD"
topics: []
tags: []
confidence: "medium"
generation_method: "prompt_pack"
---

# Summary

placeholder
```

# Source Notes

(none)
"""

MINIMAL_SYNTHESIS = """\
---
title: "Test Topic"
note_type: "topic"
compiled_from: []
date_compiled: "2026-04-08"
topics: []
tags: []
confidence: "medium"
generation_method: "prompt_pack"
---

# Summary

Synthesized content here.

# Key Insights

- Insight one.

# Related Concepts

# Source Notes

# Lineage

Generated by test.
"""


class RunTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temp_dir = tempfile.TemporaryDirectory()
        self.root = Path(self.temp_dir.name)

        for relative in [
            "compiled/topics",
            "compiled/source_summaries",
            "compiled/concepts",
            "outputs/answers",
            "outputs/reports",
            "metadata/prompts",
            "metadata",
            "tmp",
        ]:
            (self.root / relative).mkdir(parents=True, exist_ok=True)

        (self.root / "metadata" / "topic-registry.json").write_text(
            json.dumps({"topics": []}), encoding="utf-8"
        )

        self.prompt_pack_path = self.root / "metadata" / "prompts" / "compile-test-topic.md"
        self.prompt_pack_path.write_text(MINIMAL_PROMPT_PACK, encoding="utf-8")

    def tearDown(self) -> None:
        self.temp_dir.cleanup()

    def _patch_run(self, synthesis_text: str, model: str = "qwen2.5:14b") -> int:
        """Run the driver with mocked Ollama calls and a patched ROOT."""
        tokens = [synthesis_text]

        with (
            patch("scripts.llm_driver.ROOT", self.root),
            patch("scripts.llm_driver.TMP_OUTPUT", self.root / "tmp" / "synthesis-output.md"),
            patch("urllib.request.urlopen") as mock_urlopen,
        ):
            # First urlopen call → /api/tags, second → /api/generate
            mock_urlopen.side_effect = [
                _make_tags_response([model]),
                _make_stream_response(tokens),
            ]
            return run(
                prompt_pack=self.prompt_pack_path,
                model=model,
                output_type="compiled",
                title_override="",
                force=False,
            )

    def test_run_creates_artifact(self) -> None:
        rc = self._patch_run(MINIMAL_SYNTHESIS)
        self.assertEqual(rc, 0)
        artifact = self.root / "compiled" / "topics" / "test-topic.md"
        self.assertTrue(artifact.exists(), f"Expected artifact at {artifact}")

    def test_run_sets_generation_method_ollama_local(self) -> None:
        self._patch_run(MINIMAL_SYNTHESIS)
        artifact = self.root / "compiled" / "topics" / "test-topic.md"
        content = artifact.read_text(encoding="utf-8")
        self.assertIn('generation_method: "ollama_local"', content)

    def test_run_saves_tmp_file(self) -> None:
        self._patch_run(MINIMAL_SYNTHESIS)
        tmp = self.root / "tmp" / "synthesis-output.md"
        self.assertTrue(tmp.exists())
        self.assertIn("Synthesized content", tmp.read_text(encoding="utf-8"))

    def test_run_returns_error_when_prompt_pack_missing(self) -> None:
        rc = run(
            prompt_pack=self.root / "metadata" / "prompts" / "nonexistent.md",
            model="qwen2.5:14b",
            output_type="compiled",
            title_override="",
            force=False,
        )
        self.assertEqual(rc, 1)

    def test_run_returns_error_when_model_unavailable(self) -> None:
        with (
            patch("scripts.llm_driver.ROOT", self.root),
            patch("urllib.request.urlopen", return_value=_make_tags_response(["llama3.1:8b"])),
        ):
            rc = run(
                prompt_pack=self.prompt_pack_path,
                model="qwen2.5:14b",
                output_type="compiled",
                title_override="",
                force=False,
            )
        self.assertEqual(rc, 1)

    def test_run_force_overwrites_existing_artifact(self) -> None:
        self._patch_run(MINIMAL_SYNTHESIS)
        # Second run without force should fail
        rc = self._patch_run(MINIMAL_SYNTHESIS)
        self.assertEqual(rc, 1)
        # Third run with force should succeed
        with (
            patch("scripts.llm_driver.ROOT", self.root),
            patch("scripts.llm_driver.TMP_OUTPUT", self.root / "tmp" / "synthesis-output.md"),
            patch("urllib.request.urlopen") as mock_urlopen,
        ):
            mock_urlopen.side_effect = [
                _make_tags_response(["qwen2.5:14b"]),
                _make_stream_response([MINIMAL_SYNTHESIS]),
            ]
            rc = run(
                prompt_pack=self.prompt_pack_path,
                model="qwen2.5:14b",
                output_type="compiled",
                title_override="",
                force=True,
            )
        self.assertEqual(rc, 0)


if __name__ == "__main__":
    unittest.main()
